# Generated by Django 5.0.6 on 2024-07-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_item_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_image',
        ),
    ]
