# Generated by Django 5.0.6 on 2024-07-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_remove_item_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/OIP.kRfblRpg8bm4PcJqIF6SRgHaFj?rs=1&pid=ImgDetMain', max_length=500),
        ),
    ]
